version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: us.icr.io/cv-studio-access/faster-r-cnn3:latest
    working_dir: /app
    ports:
      - "8080:8080"
